### ISSUE TITLE
Update to 2.92

### ISSUE THREAD

**Issue by Forage** [ssurba/transmission-readynas-arm-legacy#1]
Hi,

Transmission finally came with a new version again. Will there be an update of your add-on to Transmission 2.92?

Thanks in advance!

**Comment by ssurba** [comment]
Sure, I'm starting working on it. Thanks for the reminder.

**Comment by ssurba** [comment]
v2.92 is out, please test it.

**Comment by Forage** [comment]
Works like a charm! Thank you!
